export const WEATHER_REFRESH = 'weather_refresh'
export const WEATHER_REFRESH_POST = 'weather_refresh_post'
export const WEATHER_FUTURE_POST = 'weather_future_post'
export const WEATHER_SETUP = 'weather_setup'
export const WEATHER_SETUP_POST = 'weather_setup_post'